const PRODUCTS = [
  {
    id: 1,
    name: "iPhone 16 Pro Max",
    brand: "Apple",
    category: "Smartphones",
    price: 134900,
    oldPrice: 159900,
    discount: 16,
    rating: 4.9,
    reviews: 8420,
    stock: "in",
    featured: true,
    trending: true,
    image: "images/products/01-iphone-16-pro-max.jpg",
    storeLink: "https://www.apple.com/in/shop/buy-iphone/iphone-16-pro",
    compareLink: "https://www.gsmarena.com/apple_iphone_16_pro_max-12421.php",
    summary: "Titanium design. A18 Pro chip. 48MP Fusion Camera with 5x optical zoom. Available in 4 stunning colors.",
    specs: {
      "Display": "6.9\" Super Retina XDR",
      "Chip": "Apple A18 Pro",
      "Camera": "48MP + 48MP + 12MP",
      "Battery": "4685 mAh",
      "Storage": "256GB / 512GB / 1TB",
      "OS": "iOS 18"
    },
    features: [
      "ProMotion 120Hz Always-On display",
      "Action button customization",
      "USB 3 speed with USB-C",
      "Ceramic Shield front glass",
      "Satellite connectivity support"
    ]
  },
  {
    id: 2,
    name: "Samsung Galaxy S25 Ultra",
    brand: "Samsung",
    category: "Smartphones",
    price: 129999,
    oldPrice: 149999,
    discount: 13,
    rating: 4.8,
    reviews: 6210,
    stock: "in",
    featured: true,
    trending: false,
    image: "images/products/02-samsung-galaxy-s25-ultra.jpg",
    storeLink: "https://www.samsung.com/in/smartphones/galaxy-s/galaxy-s25-ultra/",
    compareLink: "https://www.gsmarena.com/samsung_galaxy_s25_ultra-12769.php",
    summary: "Built-in S Pen. Snapdragon 8 Elite. 200MP quad camera system. The ultimate Galaxy AI powerhouse.",
    specs: {
      "Display": "6.9\" Dynamic AMOLED 2X",
      "Chip": "Snapdragon 8 Elite",
      "Camera": "200MP + 50MP + 10MP + 12MP",
      "Battery": "5000 mAh",
      "Storage": "256GB / 512GB / 1TB",
      "OS": "Android 15 (One UI 7)"
    },
    features: [
      "Built-in S Pen with Galaxy AI",
      "Titanium frame construction",
      "200MP main camera with AI zoom",
      "Circle to Search with Google",
      "45W super fast charging"
    ]
  },
  {
    id: 3,
    name: "OnePlus 13",
    brand: "OnePlus",
    category: "Smartphones",
    price: 69999,
    oldPrice: 84999,
    discount: 18,
    rating: 4.7,
    reviews: 3890,
    stock: "in",
    featured: false,
    trending: true,
    image: "images/products/03-oneplus-13.png",
    storeLink: "https://www.oneplus.in/oneplus-13",
    compareLink: "https://www.gsmarena.com/oneplus_13-12740.php",
    summary: "Snapdragon 8 Elite • Hasselblad Triple Camera • 100W SUPERVOOC fast charge in 28 min.",
    specs: {
      "Display": "6.82\" LTPO AMOLED 120Hz",
      "Chip": "Snapdragon 8 Elite",
      "Camera": "50MP + 50MP + 50MP Hasselblad",
      "Battery": "6000 mAh",
      "Storage": "256GB / 512GB",
      "OS": "OxygenOS 15 (Android 15)"
    },
    features: [
      "Hasselblad-tuned triple camera system",
      "100W SUPERVOOC + 50W AIRVOOC",
      "Alert slider for quick profile switching",
      "6000mAh silicon-carbon battery",
      "IP69 water resistance"
    ]
  },
  {
    id: 4,
    name: "Realme GT 6",
    brand: "Realme",
    category: "Smartphones",
    price: 39999,
    oldPrice: 49999,
    discount: 20,
    rating: 4.5,
    reviews: 2110,
    stock: "low",
    featured: false,
    trending: true,
    image: "images/products/04-realme-gt-6.jpg",
    storeLink: "https://www.realme.com/in/realme-gt6",
    compareLink: "https://www.gsmarena.com/realme_gt_6-12404.php",
    summary: "Snapdragon 8s Gen 3 • 120W ultra-fast charging • 6.78\" 120Hz LTPO AMOLED • 50MP Sony IMX906",
    specs: {
      "Display": "6.78\" LTPO AMOLED 120Hz",
      "Chip": "Snapdragon 8s Gen 3",
      "Camera": "50MP Sony IMX906",
      "Battery": "5500 mAh",
      "Storage": "128GB / 256GB",
      "OS": "Realme UI 5.0 (Android 14)"
    },
    features: [
      "120W SuperVOOC fast charging (28 min full)",
      "Sony IMX906 main sensor",
      "AI-powered camera features",
      "Snapdragon 8s Gen 3 flagship chip",
      "IP65 water resistance"
    ]
  },
  {
    id: 5,
    name: "AirPods Pro 3",
    brand: "Apple",
    category: "Earbuds",
    price: 26900,
    oldPrice: 29900,
    discount: 10,
    rating: 4.9,
    reviews: 12340,
    stock: "in",
    featured: true,
    trending: true,
    image: "images/products/05-airpods-pro-3.jpg",
    storeLink: "https://www.apple.com/in/shop/buy-airpods/airpods-pro",
    compareLink: "https://www.smartprix.com/mobiles/apple-airpods-pro-pid7748289.html",
    summary: "Active Noise Cancellation, Transparency mode, Hearing Health features. Spatial audio with dynamic head tracking.",
    specs: {
      "Chip": "H2 + U1",
      "ANC": "Active Noise Cancellation",
      "Battery": "6hr (30hr with case)",
      "Resistance": "IPX4",
      "Connectivity": "Bluetooth 5.3",
      "Charging": "MagSafe / Lightning / USB-C"
    },
    features: [
      "Computational Audio with H2 chip",
      "Adaptive Transparency mode",
      "Personalized Spatial Audio",
      "Hearing aid-grade amplification",
      "Swipe to control volume"
    ]
  },
  {
    id: 6,
    name: "Galaxy Buds3 Pro",
    brand: "Samsung",
    category: "Earbuds",
    price: 17999,
    oldPrice: 22999,
    discount: 22,
    rating: 4.7,
    reviews: 4590,
    stock: "in",
    featured: false,
    trending: true,
    image: "images/products/06-galaxy-buds3-pro.jpg",
    storeLink: "https://www.samsung.com/in/audio-sound/galaxy-buds/galaxy-buds3-pro/",
    compareLink: "https://www.smartprix.com/mobiles/samsung-galaxy-buds3-pro-pid10614773.html",
    summary: "Blade-like open design. Intelligent ANC. 360° audio. Galaxy AI with live translate in 16 languages.",
    specs: {
      "Driver": "10mm woofer + 6.1mm tweeter",
      "ANC": "Intelligent ANC (up to 24dB)",
      "Battery": "6hr (30hr with case)",
      "Resistance": "IP57",
      "Connectivity": "Bluetooth 5.4",
      "Codec": "SSC UHQ, AAC, SBC"
    },
    features: [
      "Blade-type open design",
      "360° Audio with Galaxy AI",
      "Live Translate for phone calls",
      "Adaptive EQ per ear",
      "Temperature & humidity sensor"
    ]
  },
  {
    id: 7,
    name: "Sony WF-1000XM5",
    brand: "Sony",
    category: "Earbuds",
    price: 21990,
    oldPrice: 29990,
    discount: 27,
    rating: 4.8,
    reviews: 7620,
    stock: "in",
    featured: true,
    trending: false,
    image: "images/products/07-sony-wf-1000xm5.png",
    storeLink: "https://www.sony.co.in/en/headphones/products/WF-1000XM5",
    compareLink: "https://www.smartprix.com/mobiles/sony-wf-1000xm5-pid8906703.html",
    summary: "World's smallest & lightest WF with top-end performance. Integrated Processor V2 for ultimate ANC.",
    specs: {
      "Driver": "8.4mm Carbon Fibre composite",
      "ANC": "Dual Noise Sensor",
      "Battery": "8hr (36hr with case)",
      "Resistance": "IPX4",
      "Connectivity": "Bluetooth 5.3",
      "Codec": "LDAC, AAC, SBC"
    },
    features: [
      "Industry-leading noise cancellation",
      "LDAC Hi-Res Audio Wireless",
      "Auto NC Optimizer",
      "Speak-to-chat automatic pause",
      "360 Reality Audio support"
    ]
  },
  {
    id: 8,
    name: "Samsung Galaxy Watch Ultra",
    brand: "Samsung",
    category: "Smartwatches",
    price: 71999,
    oldPrice: 89999,
    discount: 20,
    rating: 4.8,
    reviews: 3210,
    stock: "in",
    featured: true,
    trending: true,
    image: "images/products/08-samsung-galaxy-watch-ultra.jpg",
    storeLink: "https://www.samsung.com/in/watches/galaxy-watch/galaxy-watch-ultra/",
    compareLink: "https://www.91mobiles.com/samsung-galaxy-watch-ultra-price-in-india",
    summary: "Military-grade titanium. Dual speakers. 10ATM water resistance. Advanced health sensors with BioActive Pro.",
    specs: {
      "Case": "47mm Titanium",
      "Display": "1.5\" AMOLED 480×480",
      "Battery": "590 mAh (3 days+)",
      "Resistance": "10ATM + IP68 + MIL-STD-810",
      "OS": "Wear OS 5 / One UI Watch 7",
      "Sensors": "BioActive Pro + ECG + GPS"
    },
    features: [
      "Titanium Grade 4 construction",
      "10ATM water resistance (100m)",
      "Dual speaker system",
      "Advanced sleep coaching",
      "Emergency SOS with satellite"
    ]
  },
  {
    id: 9,
    name: "Apple Watch Series 10",
    brand: "Apple",
    category: "Smartwatches",
    price: 44900,
    oldPrice: 49900,
    discount: 10,
    rating: 4.9,
    reviews: 9810,
    stock: "in",
    featured: false,
    trending: false,
    image: "images/products/09-apple-watch-series-10.jpg",
    storeLink: "https://www.apple.com/in/shop/buy-watch/apple-watch",
    compareLink: "https://www.91mobiles.com/apple-watch-series-10-price-in-india",
    summary: "Thinnest Apple Watch ever. Carbon neutral option. Crash detection, ECG, and Blood Oxygen monitoring.",
    specs: {
      "Case": "46mm Aluminum / Titanium",
      "Display": "Always-On Retina LTPO OLED",
      "Chip": "S10 SiP",
      "Battery": "18hr (36hr low power)",
      "Resistance": "50m WR (IP6X dust)",
      "OS": "watchOS 11"
    },
    features: [
      "Thinnest Apple Watch design ever",
      "Crash Detection + Emergency SOS",
      "FDA-approved ECG app",
      "Sleep Apnea detection",
      "Carbon neutral aluminum options"
    ]
  },
  {
    id: 10,
    name: "Amazfit GTR 4",
    brand: "Amazfit",
    category: "Smartwatches",
    price: 13999,
    oldPrice: 19999,
    discount: 30,
    rating: 4.4,
    reviews: 5670,
    stock: "in",
    featured: false,
    trending: true,
    image: "images/products/10-amazfit-gtr-4.jpg",
    storeLink: "https://www.amazfit.com/en/gtr4",
    compareLink: "https://www.91mobiles.com/amazfit-gtr-4-price-in-india",
    summary: "14-day battery life. Dual-frequency GPS. BioTracker 4.0 PPG sensor. 150+ sports modes.",
    specs: {
      "Case": "46mm Aluminum",
      "Display": "1.43\" AMOLED 466×466",
      "Battery": "14 days (2 days GPS)",
      "Resistance": "5ATM",
      "OS": "Zepp OS 2",
      "GPS": "L1+L5 Dual-band"
    },
    features: [
      "Dual-frequency GPS accuracy",
      "150+ built-in sports modes",
      "Continuous SpO2 monitoring",
      "AI-powered sleep analysis",
      "Alexa built-in"
    ]
  },
  {
    id: 11,
    name: "iPad Air M3 (11-inch)",
    brand: "Apple",
    category: "Tablets",
    price: 69900,
    oldPrice: 79900,
    discount: 13,
    rating: 4.9,
    reviews: 4230,
    stock: "in",
    featured: true,
    trending: false,
    image: "images/products/11-ipad-air-m3-11-inch.jpg",
    storeLink: "https://www.apple.com/in/shop/buy-ipad/ipad-air",
    compareLink: "https://www.91mobiles.com/apple-ipad-air-m3-price-in-india",
    summary: "M3 chip for next-level performance. Liquid Retina display. Works with Apple Pencil Pro and Magic Keyboard.",
    specs: {
      "Chip": "Apple M3",
      "Display": "11\" Liquid Retina (2360×1640)",
      "Camera": "12MP Wide + 12MP Ultra Wide",
      "Battery": "28hr video",
      "Storage": "128GB – 1TB",
      "Connectivity": "Wi-Fi 6E + Optional 5G"
    },
    features: [
      "Apple M3 chip performance",
      "Apple Pencil Pro support",
      "Magic Keyboard compatibility",
      "Liquid Retina display with P3 color",
      "Center Stage FaceTime camera"
    ]
  },
  {
    id: 12,
    name: "Samsung Galaxy Tab S10",
    brand: "Samsung",
    category: "Tablets",
    price: 79999,
    oldPrice: 95999,
    discount: 17,
    rating: 4.7,
    reviews: 2980,
    stock: "in",
    featured: false,
    trending: false,
    image: "images/products/12-samsung-galaxy-tab-s10.jpg",
    storeLink: "https://www.samsung.com/in/tablets/galaxy-tab-s/galaxy-tab-s10/",
    compareLink: "https://www.smartprix.com/mobiles/samsung-galaxy-tab-s10-pid10574697.html",
    summary: "Snapdragon 8 Gen 3. Anti-Reflective Display. S Pen included. Galaxy AI with Note Assist.",
    specs: {
      "Chip": "Snapdragon 8 Gen 3",
      "Display": "11\" Dynamic AMOLED 2X",
      "Camera": "13MP + 8MP",
      "Battery": "8000 mAh",
      "Storage": "128GB / 256GB",
      "OS": "Android 14 (One UI 6.1.1)"
    },
    features: [
      "S Pen included (Bluetooth)",
      "Anti-Reflective display coating",
      "Galaxy AI – Note Assist",
      "IP68 water and dust resistance",
      "Multi-window and DeX mode"
    ]
  },
  {
    id: 13,
    name: "MacBook Air M4 (15-inch)",
    brand: "Apple",
    category: "Laptops",
    price: 139900,
    oldPrice: 159900,
    discount: 13,
    rating: 4.9,
    reviews: 6780,
    stock: "in",
    featured: true,
    trending: true,
    image: "images/products/13-macbook-air-m4-15-inch.jpg",
    storeLink: "https://www.apple.com/in/shop/buy-mac/macbook-air/15-inch",
    compareLink: "https://www.smartprix.com/mobiles/apple-macbook-air-15-m4-pid12376649.html",
    summary: "M4 chip. 18-hour battery. Liquid Retina display. Fanless design with up to 32GB unified memory.",
    specs: {
      "Chip": "Apple M4 (10-core CPU)",
      "Display": "15.3\" Liquid Retina",
      "RAM": "16GB / 24GB / 32GB",
      "Storage": "256GB – 2TB SSD",
      "Battery": "18 hrs",
      "Ports": "2× Thunderbolt 4, MagSafe 3"
    },
    features: [
      "Apple M4 chip with Neural Engine",
      "Fanless silent operation",
      "Liquid Retina display with True Tone",
      "1080p FaceTime HD camera",
      "MagSafe 3 charging"
    ]
  },
  {
    id: 14,
    name: "Dell XPS 15 (9530)",
    brand: "Dell",
    category: "Laptops",
    price: 149999,
    oldPrice: 179999,
    discount: 17,
    rating: 4.6,
    reviews: 3120,
    stock: "low",
    featured: false,
    trending: false,
    image: "images/products/14-dell-xps-15-9530.jpg",
    storeLink: "https://www.dell.com/en-in/shop/laptops/xps-15-laptop/spd/xps-15-9530-laptop",
    compareLink: "https://www.smartprix.com/mobiles/dell-xps-15-9530-pid9277773.html",
    summary: "Intel Core i9-13900H. NVIDIA GeForce RTX 4070. 15.6\" 3.5K OLED touch display. Thunderbolt 4.",
    specs: {
      "CPU": "Intel Core i9-13900H",
      "GPU": "NVIDIA RTX 4070 8GB",
      "Display": "15.6\" OLED 3.5K Touch",
      "RAM": "32GB DDR5",
      "Storage": "1TB NVMe SSD",
      "Battery": "86Whr (13hrs)"
    },
    features: [
      "3.5K OLED touchscreen display",
      "NVIDIA GeForce RTX 4070",
      "Thunderbolt 4 ports (×2)",
      "CNC aluminium chassis",
      "DDR5 memory for speed"
    ]
  },
  {
    id: 15,
    name: "Anker 733 Power Bank (GaNPrime 65W)",
    brand: "Anker",
    category: "Power Banks",
    price: 7999,
    oldPrice: 10999,
    discount: 27,
    rating: 4.8,
    reviews: 8920,
    stock: "in",
    featured: false,
    trending: true,
    image: "images/products/15-anker-733-power-bank-ganprime-65w.jpg",
    storeLink: "https://www.anker.com/products/anker-733-power-bank",
    compareLink: "https://www.91mobiles.com/anker-733-power-bank-ganprime-65w-price-in-india",
    summary: "2-in-1 power bank + GaN 65W wall charger. 10,000mAh. Charges MacBook Air in 2.3 hours.",
    specs: {
      "Capacity": "10,000mAh",
      "Wall Output": "65W (GaN)",
      "Bank Output": "30W (USB-C)",
      "Inputs": "USB-C 30W",
      "Ports": "2× USB-C + 1× USB-A",
      "Weight": "223g"
    },
    features: [
      "2-in-1 power bank + wall charger",
      "65W GaN technology",
      "Charges MacBook Air in 2.3hrs",
      "PowerIQ 4.0 universal charging",
      "LED display with battery %"
    ]
  },
  {
    id: 16,
    name: "Anker PowerCore 20000 PD",
    brand: "Anker",
    category: "Power Banks",
    price: 4499,
    oldPrice: 5999,
    discount: 25,
    rating: 4.7,
    reviews: 14300,
    stock: "in",
    featured: false,
    trending: false,
    image: "images/products/16-anker-powercore-20000-pd.jpg",
    storeLink: "https://www.anker.com/products/anker-powercore-20000-pd",
    compareLink: "https://www.91mobiles.com/anker-powercore-20000-pd-price-in-india",
    summary: "Massive 20,000mAh capacity. 22.5W fast charging. 3-port simultaneous charging for all devices.",
    specs: {
      "Capacity": "20,000mAh",
      "Max Output": "22.5W (USB-C)",
      "Input": "USB-C 15W",
      "Ports": "1× USB-C + 2× USB-A",
      "Charges iPhone": "4.6× times",
      "Weight": "354g"
    },
    features: [
      "20,000mAh for multiple charges",
      "22.5W USB-C fast charging",
      "Charge 3 devices simultaneously",
      "LED power indicator",
      "Airline carry-on compliant"
    ]
  },
  {
    id: 17,
    name: "UGREEN Nexode 200W GaN",
    brand: "UGREEN",
    category: "Chargers",
    price: 8999,
    oldPrice: 12999,
    discount: 31,
    rating: 4.8,
    reviews: 3420,
    stock: "in",
    featured: false,
    trending: false,
    image: "images/products/17-ugreen-nexode-200w-gan.jpg",
    storeLink: "https://www.ugreen.com/products/ugreen-nexode-200w-usb-c-charger",
    compareLink: "https://www.91mobiles.com/ugreen-nexode-200w-gan-charger-price-in-india",
    summary: "200W GaN. 4-port desk charger. Charges MacBook Pro, iPad, iPhone, and Android simultaneously.",
    specs: {
      "Total Output": "200W",
      "Ports": "3× USB-C + 1× USB-A",
      "Protocol": "PD 3.0 / PPS / QC 4+",
      "Technology": "GaN II (Gallium Nitride)",
      "Foldable Plug": "Yes",
      "Compatibility": "Universal"
    },
    features: [
      "200W total power output",
      "4 ports for simultaneous charging",
      "GaN II technology runs cooler",
      "Universal compatibility (USB PD)",
      "Compact foldable plug design"
    ]
  },
  {
    id: 18,
    name: "UGREEN Nexode 45W USB-C Charger",
    brand: "UGREEN",
    category: "Chargers",
    price: 1999,
    oldPrice: 2999,
    discount: 33,
    rating: 4.7,
    reviews: 6780,
    stock: "in",
    featured: false,
    trending: false,
    image: "images/products/18-ugreen-nexode-45w-usb-c-charger.jpg",
    storeLink: "https://www.ugreen.com/products/ugreen-nexode-45w-usb-c-charger",
    compareLink: "https://www.91mobiles.com/ugreen-nexode-45w-usb-c-charger-price-in-india",
    summary: "45W GaN mini charger. Charges iPhone 16 Pro to 50% in just 28 minutes. 2-port USB-C.",
    specs: {
      "Output": "45W (single) / 45W (dual)",
      "Ports": "2× USB-C",
      "Protocol": "PD 3.1, PPS, Apple Fast Charge",
      "Technology": "GaN",
      "Foldable Plug": "Yes",
      "Size": "Compact (45×45×28mm)"
    },
    features: [
      "45W GaN super fast charging",
      "Charges iPhone 16 to 50% in 28 min",
      "Dual USB-C ports",
      "Ultra-compact travel size",
      "Universal compatibility"
    ]
  },
  {
    id: 19,
    name: "Spigen Tough Armor iPhone 16 Pro Case",
    brand: "Spigen",
    category: "Accessories",
    price: 1899,
    oldPrice: 2999,
    discount: 37,
    rating: 4.7,
    reviews: 22190,
    stock: "in",
    featured: false,
    trending: false,
    image: "images/products/19-spigen-tough-armor-iphone-16-pro-case.jpg",
    storeLink: "https://www.spigen.com/collections/iphone-16-pro-case/products/iphone-16-pro-case-tough-armor",
    compareLink: "https://www.91mobiles.com/spigen-tough-armor-iphone-16-pro-case-price-in-india",
    summary: "Military-grade drop protection. Kickstand included. MagSafe compatible. Dual-layer shockproof design.",
    specs: {
      "Model": "iPhone 16 Pro",
      "Protection": "MIL-STD-810G",
      "Material": "TPU + PC",
      "MagSafe": "Compatible",
      "Kickstand": "Included",
      "Drop Test": "12 feet certified"
    },
    features: [
      "Military-grade drop protection",
      "Built-in kickstand",
      "MagSafe compatible",
      "Dual-layer armor construction",
      "Precise port cutouts"
    ]
  },
  {
    id: 20,
    name: "Spigen Ultra Hybrid Clear Case",
    brand: "Spigen",
    category: "Accessories",
    price: 1399,
    oldPrice: 1999,
    discount: 30,
    rating: 4.6,
    reviews: 31240,
    stock: "in",
    featured: false,
    trending: false,
    image: "images/products/20-spigen-ultra-hybrid-clear-case.jpg",
    storeLink: "https://www.spigen.com/collections/iphone-16-case/products/iphone-16-case-ultra-hybrid",
    compareLink: "https://www.91mobiles.com/spigen-ultra-hybrid-clear-case-price-in-india",
    summary: "Crystal clear protection. Anti-yellowing technology. Shows off your iPhone's original design beautifully.",
    specs: {
      "Model": "iPhone 13 / 14 / 15 / 16",
      "Material": "Thermoplastic polyurethane",
      "Anti-Yellow": "Yes",
      "MagSafe": "Optional variant",
      "Drop Test": "Military-grade",
      "Thickness": "1mm back"
    },
    features: [
      "Anti-yellowing TPU material",
      "Military-grade drop protection",
      "Crystal clear back panel",
      "Raised lip for screen/camera",
      "Slim fit design"
    ]
  },
  {
    id: 21,
    name: "JBL Flip 6",
    brand: "JBL",
    category: "Speakers",
    price: 9999,
    oldPrice: 13999,
    discount: 29,
    rating: 4.8,
    reviews: 17540,
    stock: "in",
    featured: true,
    trending: true,
    image: "images/products/21-jbl-flip-6.jpg",
    storeLink: "https://in.jbl.com/bluetooth-speakers/JBL+FLIP+6.html",
    compareLink: "https://www.smartprix.com/mobiles/jbl-flip-6-pid8262143.html",
    summary: "IP67 waterproof. 12 hours battery. PartyBoost to connect two JBL speakers. Bold powerful sound.",
    specs: {
      "Driver": "2-way speaker system",
      "Battery": "12 hours",
      "Waterproofing": "IP67",
      "Connectivity": "Bluetooth 5.1",
      "PartyBoost": "Yes (up to 100 speakers)",
      "Weight": "550g"
    },
    features: [
      "IP67 fully waterproof + dustproof",
      "12 hours of playtime",
      "PartyBoost multi-speaker sync",
      "Racetrack-shaped subwoofer",
      "USB-C fast charging"
    ]
  },
  {
    id: 22,
    name: "Sony SRS-XB33",
    brand: "Sony",
    category: "Speakers",
    price: 7990,
    oldPrice: 12990,
    discount: 38,
    rating: 4.6,
    reviews: 8930,
    stock: "in",
    featured: false,
    trending: false,
    image: "images/products/22-sony-srs-xb33.png",
    storeLink: "https://www.sony.co.in/en/audio/products/SRS-XB33",
    compareLink: "https://www.smartprix.com/mobiles/sony-srs-xb33-pid7457303.html",
    summary: "24-hour battery. IP67 waterproof. Extra Bass technology. Party Connect for up to 100 speakers.",
    specs: {
      "Battery": "24 hours",
      "Waterproofing": "IP67",
      "Connectivity": "Bluetooth 5.0 + NFC",
      "Extra Bass": "Yes",
      "Party Connect": "Up to 100 speakers",
      "Colors": "Black, Blue, Red, Green"
    },
    features: [
      "24-hour marathon battery life",
      "IP67 waterproof and dustproof",
      "Sony EXTRA BASS technology",
      "Party Connect wireless party",
      "Stereo pairing support"
    ]
  },
  {
    id: 23,
    name: "Logitech G Pro X Superlight 2",
    brand: "Logitech G",
    category: "Gaming Gear",
    price: 14999,
    oldPrice: 19999,
    discount: 25,
    rating: 4.9,
    reviews: 6210,
    stock: "in",
    featured: true,
    trending: true,
    image: "images/products/23-logitech-g-pro-x-superlight-2.jpg",
    storeLink: "https://www.logitechg.com/en-in/products/gaming-mice/pro-x2-superlight-wireless-mouse.html",
    compareLink: "https://www.91mobiles.com/logitech-g-pro-x-superlight-2-price-in-india",
    summary: "Only 60g. HERO 2 25K sensor. 95hr battery. LIGHTSPEED wireless. Trusted by world's best pro players.",
    specs: {
      "Weight": "60g (lightest ever)",
      "Sensor": "HERO 2 25K DPI",
      "Battery": "95 hours",
      "Connectivity": "LIGHTSPEED Wireless",
      "Switches": "Optical (60M clicks)",
      "Feet": "Zero-additive PTFE"
    },
    features: [
      "Weighs only 60g (feather-light)",
      "HERO 2 sensor (up to 25,600 DPI)",
      "95-hour LIGHTSPEED battery",
      "Zero-additive PTFE feet",
      "Used by pro esports players"
    ]
  },
  {
    id: 24,
    name: "Razer BlackShark V2 X",
    brand: "Razer",
    category: "Gaming Gear",
    price: 3999,
    oldPrice: 5499,
    discount: 27,
    rating: 4.6,
    reviews: 9840,
    stock: "in",
    featured: false,
    trending: false,
    image: "images/products/24-razer-blackshark-v2-x.jpg",
    storeLink: "https://www.razer.com/in-en/gaming-headsets/razer-blackshark-v2-x",
    compareLink: "https://www.91mobiles.com/razer-blackshark-v2-x-price-in-india",
    summary: "7.1 Surround Sound. 50mm TriForce drivers. Cardioid mic. Ultra-light 240g. For PC/PS/Xbox/Switch.",
    specs: {
      "Drivers": "50mm Razer TriForce",
      "Surround": "THX 7.1 Surround Sound",
      "Microphone": "Cardioid + noise filter",
      "Connection": "3.5mm + USB adapter",
      "Weight": "240g",
      "Compatibility": "PC, PS5, Xbox, Switch, Mobile"
    },
    features: [
      "THX 7.1 Surround Sound",
      "50mm TriForce tuned drivers",
      "Cardioid microphone",
      "FlowKnit Memory Foam cushion",
      "Universal 3.5mm compatibility"
    ]
  }
];
function formatINR(amount) {
  return '₹' + amount.toLocaleString('en-IN');
}
function generateStars(rating) {
  const full = Math.floor(rating);
  const half = rating % 1 >= 0.5 ? 1 : 0;
  const empty = 5 - full - half;
  return '★'.repeat(full) + (half ? '½' : '') + '☆'.repeat(empty);
}